const setupParams=new URLSearchParams(location.hash.slice(1));let setupToken=setupParams.get('setup_token');let starting=false;let passwordLinkMode=new URLSearchParams(location.hash.slice(1)).get('type')==='recovery';
function showLogin(message=''){document.getElementById('auth-loading').hidden=true;document.getElementById('secure-dialog')?.remove();document.querySelector('.sidebar').hidden=true;document.querySelector('.main-shell').hidden=true;document.getElementById('login-screen').hidden=false;document.getElementById('login-error').textContent=message;}
async function startSecureApp(){if(starting)return;starting=true;try{if(setupToken){const token=setupToken;setupToken=null;const verified=await db.auth.verifyOtp({token_hash:token,type:'recovery'});if(verified.error){showLogin('Ο σύνδεσμος έχει λήξει ή έχει ήδη χρησιμοποιηθεί. Χρειάζεται νέος σύνδεσμος.');return;}passwordLinkMode=true;history.replaceState(null,'',location.pathname+location.search);}const {data:{session}}=await db.auth.getSession();if(!session){const linkError=new URLSearchParams(location.hash.slice(1)).get('error_description');showLogin(linkError?'Ο σύνδεσμος έχει λήξει ή έχει ήδη χρησιμοποιηθεί. Χρειάζεται νέος σύνδεσμος.':' ');return;}if(passwordLinkMode){showPasswordSetup();return;}const current=await db.auth.getUser();if(current.error)throw current.error;const member=await db.from('mediuse_members').select('needs_password').eq('user_id',current.data.user.id);if(member.error)throw member.error;if(member.data[0]?.needs_password){showPasswordSetup();return;}await loadFromCloud();document.getElementById('auth-loading').hidden=true;document.getElementById('login-screen').hidden=true;document.querySelector('.sidebar').hidden=false;document.querySelector('.main-shell').hidden=false;localStorage.removeItem('mediuse_bk');}catch(error){showLogin(error.message==='access_denied'?'Ο λογαριασμός δεν έχει πρόσβαση στο MediUse.':error.message==='not_active'?'Η νέα έκδοση προετοιμάζεται. Η πρόσβασή σας θα ενεργοποιηθεί με την ολοκλήρωση της μετάβασης.':'Δεν ήταν δυνατή η φόρτωση. Δοκιμάστε ξανά.');}finally{starting=false;}}
document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();const button=document.getElementById('login-submit');button.disabled=true;try{const {error}=await db.auth.signInWithPassword({email:document.getElementById('login-email').value.trim(),password:document.getElementById('login-password').value});if(error)throw error;document.getElementById('login-password').value='';await startSecureApp();}catch{document.getElementById('login-error').textContent='Ελέγξτε το email και τον κωδικό σας.';}finally{button.disabled=false;}};
document.getElementById('register-btn').textContent='Πρώτη σύνδεση με πρόσκληση';
document.getElementById('register-btn').onclick=()=>document.getElementById('login-error').textContent='Ανοίξτε την πρόσκληση που λάβατε με email για να ορίσετε τον κωδικό σας.';
function showPasswordSetup(){showLogin();const {d,body}=dialog('Ορισμός προσωπικού κωδικού');const form=document.createElement('form');form.className='password-setup';const label=document.createElement('label');label.textContent='Νέος κωδικός';const input=document.createElement('input');input.type='password';input.minLength=8;input.required=true;input.autocomplete='new-password';input.className='inp';label.appendChild(input);form.appendChild(label);const confirmLabel=document.createElement('label');confirmLabel.textContent='Επιβεβαίωση κωδικού';const second=input.cloneNode();confirmLabel.appendChild(second);form.appendChild(confirmLabel);const error=document.createElement('p');error.setAttribute('role','status');form.appendChild(error);const button=actionButton('Αποθήκευση κωδικού',()=>{});button.type='submit';button.onclick=null;form.appendChild(button);form.onsubmit=async e=>{e.preventDefault();if(input.value!==second.value){error.textContent='Οι κωδικοί δεν ταιριάζουν.';return;}button.disabled=true;const result=await db.auth.updateUser({password:input.value});button.disabled=false;if(result.error){error.textContent='Δεν αποθηκεύτηκε ο κωδικός. Δοκιμάστε ξανά.';return;}passwordLinkMode=false;d.close();await startSecureApp();};body.appendChild(form);}
document.getElementById('logout-btn').onclick=async()=>{if(!(await store.flush())){alert('Υπάρχουν αλλαγές που δεν έχουν αποθηκευτεί ακόμη.');return;}const {error}=await db.auth.signOut({scope:'local'});if(error){alert('Δεν ολοκληρώθηκε η αποσύνδεση.');return;}MediUseWarehouse.reset();store.ready=false;for(const c of ['tavi','boston','evar','clip']){state[c]=[];state[c+'_done']=[];}document.getElementById('records').innerHTML='';showLogin();};
db.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){passwordLinkMode=true;store.ready=false;setTimeout(()=>startSecureApp(),0);}else if(event==='SIGNED_OUT'){MediUseWarehouse.reset();store.ready=false;clearTimeout(store.retryTimer);showLogin('Συνδεθείτε για να συνεχίσετε.');}else if(event==='SIGNED_IN'){if(store.user&&store.user.id!==session?.user.id){MediUseWarehouse.reset();store.ready=false;clearTimeout(store.retryTimer);showLogin();}if(!store.ready)setTimeout(async()=>{if(store.running)await store.running;await startSecureApp();},0);}});
function dialog(title){document.getElementById('secure-dialog')?.remove();const d=document.createElement('dialog');d.id='secure-dialog';const h=document.createElement('h2');h.textContent=title;d.appendChild(h);const body=document.createElement('div');body.className='secure-dialog-body';d.appendChild(body);const close=document.createElement('button');close.className='cancel-btn';close.textContent='Κλείσιμο';close.onclick=()=>d.close();d.appendChild(close);document.body.appendChild(d);d.showModal();return {d,body};}
function actionButton(text,fn){const b=document.createElement('button');b.className='save-btn';b.textContent=text;b.onclick=fn;return b;}
document.getElementById('archive-btn').onclick=async()=>{const {body}=dialog('Διαγραμμένες εγγραφές');try{const rows=await store.archived();if(!rows.length)body.textContent='Δεν υπάρχουν διαγραμμένες εγγραφές.';for(const row of rows){const line=document.createElement('div');line.className='archive-row';const text=document.createElement('span');text.textContent=(CATS[row.category]?.label||row.category)+' · '+(row.payload.patient||'Εγγραφή')+' · '+fmtDate(row.payload.date);line.appendChild(text);line.appendChild(actionButton('Επαναφορά',async()=>{try{applyRemote(await store.restore(row));line.remove();}catch{alert('Δεν ολοκληρώθηκε η επαναφορά. Ελέγξτε τον συγχρονισμό.');}}));body.appendChild(line);}}catch{body.textContent='Δεν ήταν δυνατή η φόρτωση.';}};
document.getElementById('history-btn').onclick=async()=>{const {body}=dialog('Ιστορικό αλλαγών');try{const rows=await store.history();const labels={insert:'Προσθήκη',update:'Αλλαγή',archive:'Διαγραφή',restore:'Επαναφορά'};for(const row of rows){const line=document.createElement('p');const record=store.baseline.get(row.category+':'+row.record_id);line.textContent=new Date(row.changed_at).toLocaleString('el-GR')+' · '+labels[row.action]+' · '+(CATS[row.category]?.label||row.category)+' · '+(record?.payload.patient||'Εγγραφή')+(row.actor===store.user?.id?' · Εσείς':row.actor?' · '+(row.actor_email||'Εγκεκριμένος χρήστης'):' · Μεταφορά δεδομένων');body.appendChild(line);}}catch{body.textContent='Δεν ήταν δυνατή η φόρτωση.';}};
window.addEventListener('mediuse-conflict',async()=>{const {d,body}=dialog('Η εγγραφή έχει νεότερες αλλαγές');try{const {remote,operations}=await store.conflictRows();const map=new Map(remote.map(r=>[store.key(r),r])),choices={};const intro=document.createElement('p');intro.textContent='Οι αλλαγές σας παραμένουν αποθηκευμένες σε αυτή τη συσκευή. Επιλέξτε ποια εκδοχή θέλετε να κρατήσετε.';body.appendChild(intro);for(const change of operations){const key=store.key(change),current=map.get(key);choices[key]='remote';const block=document.createElement('div');block.className='conflict-row';const title=document.createElement('strong');title.textContent=change.payload?.patient||current?.payload.patient||'Εγγραφή';block.appendChild(title);const detail=document.createElement('p');detail.textContent=change.op==='archive'?'Δική σας αλλαγή: διαγραφή':change.op==='insert'?'Δική σας αλλαγή: νέα εγγραφή':'Δική σας αλλαγή: επεξεργασία';block.appendChild(detail);if(change.payload&&current){for(const field of CATS[change.category].fields){if(store.same(change.payload[field.id],current.payload[field.id]))continue;const p=document.createElement('p');p.textContent=field.label+': δική σας «'+(change.payload[field.id]||'—')+'» / βάση «'+(current.payload[field.id]||'—')+'»';block.appendChild(p);}}const label=document.createElement('label');label.textContent='Διατήρηση';const select=document.createElement('select');select.className='sel';[['remote','Τελευταία εκδοχή της βάσης'],['mine','Δική μου αλλαγή']].forEach(([value,text])=>{const o=document.createElement('option');o.value=value;o.textContent=text;select.appendChild(o);});if(current?.deleted_at){select.lastChild.disabled=true;const note=document.createElement('p');note.textContent='Η εγγραφή έχει διαγραφεί. Μπορείτε να την επαναφέρετε από το αρχείο διαγραφών.';block.appendChild(note);}select.onchange=()=>choices[key]=select.value;label.appendChild(select);block.appendChild(label);body.appendChild(block);}body.appendChild(actionButton('Συνέχεια',async()=>{try{if(await store.resolve(choices,remote,operations)){applyRemote(store.state());d.close();}}catch(e){alert(e.message);}}));}catch{body.textContent='Δεν ήταν δυνατή η φόρτωση. Οι αλλαγές σας διατηρούνται.';}});
setInterval(async()=>{if(document.visibilityState!=='visible'||state.editingId||state.addPanelOpen)return;try{const data=await store.refresh();if(data)applyRemote(data);}catch{}},30000);
startSecureApp();



const themeToggle=document.getElementById('theme-toggle');
function updateThemeButton(){const dark=document.documentElement.dataset.theme==='dark';themeToggle.textContent=dark?'Φωτεινό θέμα':'Σκοτεινό θέμα';themeToggle.setAttribute('aria-pressed',String(dark));document.querySelector('meta[name="theme-color"]').content=dark?'#111b27':'#f4f7fa';}
themeToggle.onclick=()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('mediuse-theme',theme);}catch{}updateThemeButton();};
updateThemeButton();

const mobileLayout=matchMedia('(max-width:850px)');
const mobileToggle=document.getElementById('mobile-menu-toggle'),mobileOptions=document.getElementById('mobile-options');
const sidebarTools=document.querySelector('.sidebar-tools'),headerActions=document.querySelector('.topbar-actions'),sortControls=document.querySelector('.sort-row'),mobileStats=document.querySelector('.stats-row');
const toolsAnchor=document.createComment('sidebar tools'),headerAnchor=document.createComment('header actions'),sortAnchor=document.createComment('sort controls');
sidebarTools.before(toolsAnchor);headerActions.before(headerAnchor);sortControls.before(sortAnchor);
function closeMobileMenu(){mobileOptions.hidden=true;mobileToggle.setAttribute('aria-expanded','false');}
function compactMobileLayout(){closeMobileMenu();if(mobileLayout.matches){mobileOptions.append(headerActions,sidebarTools);mobileStats.prepend(sortControls);}else{toolsAnchor.after(sidebarTools);headerAnchor.after(headerActions);sortAnchor.after(sortControls);}}
mobileToggle.onclick=()=>{mobileOptions.hidden=!mobileOptions.hidden;mobileToggle.setAttribute('aria-expanded',String(!mobileOptions.hidden));};
document.addEventListener('click',e=>{if(!mobileOptions.contains(e.target)&&!mobileToggle.contains(e.target))closeMobileMenu();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMobileMenu();mobileToggle.focus();}});
mobileOptions.addEventListener('click',e=>{if(e.target.closest('#archive-btn,#history-btn,#logout-btn'))closeMobileMenu();});
mobileLayout.addEventListener('change',compactMobileLayout);compactMobileLayout();

