begin;
do $$
declare member_id uuid; r jsonb; sample jsonb; before_count integer; v integer;
begin
 select user_id into member_id from public.mediuse_members where user_id is not null limit 1;
 if member_id is null then raise exception 'No member available for security test'; end if;
 select count(*) into before_count from public.mediuse_catalog_items;
 if before_count<>14536 then raise exception 'Incomplete catalog'; end if;
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',member_id,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 r:=public.mediuse_catalog_search('Q000006612');
 if (r->>'total')::int<>1 or r->'items'->0->>'code'<>'Q000006612' or r->'items'->0->>'relevance'<>'100' then raise exception 'Exact code failed'; end if;
 if r->'items'->0 ? 'purchase_qty' then raise exception 'Purchases leaked in search response'; end if;
 r:=public.mediuse_catalog_search('CA00PB3120M');
 if r->'items'->0->>'ref'<>'CA-00PB3120M' then raise exception 'Code punctuation failed'; end if;
 r:=public.mediuse_catalog_search('ΜΕΝΤΡΟΝΙΚ ΚΑΘΕΤΗΡΑΣ');
 if (r->>'total')::int<1 then raise exception 'Greek supplier/description failed'; end if;
 r:=public.mediuse_catalog_search('WK533735');
 if (r->>'total')::int<>2 then raise exception 'Duplicate refs collapsed'; end if;
 r:=public.mediuse_catalog_search('medtronic catheter','',20);
 if jsonb_array_length(r->'items')<>20 then raise exception 'Pagination failed'; end if;
 r:=public.mediuse_catalog_search('medtronic καθετήρας','ZIMMER ΒΙΟΜΕΤ ΕΛΛΑΣ ΜΟΝ/ΠΗ ΑΕ');
 if (r->>'total')::int<>0 then raise exception 'Supplier filter failed'; end if;
 if public.mediuse_catalog_search('') -> 'items' <> '[]'::jsonb then raise exception 'Blank query listed all items'; end if;
 select version into v from public.mediuse_catalog_meta where id;
 select jsonb_agg(to_jsonb(x)-'search_text'-'search_compact') into sample from (select * from public.mediuse_catalog_items order by code limit 2) x;
 r:=public.mediuse_catalog_preview(sample);
 if (r->>'added')::int<>0 or (r->>'changed')::int<>0 or (r->>'removed')::int<>before_count-2 then raise exception 'Preview failed'; end if;
 begin perform public.mediuse_catalog_import(sample,'test',v-1);raise exception 'Conflict accepted';exception when others then if sqlerrm<>'catalog_conflict' then raise;end if;end;
 begin perform public.mediuse_catalog_preview(sample || jsonb_build_array(sample->0));raise exception 'Duplicate accepted';exception when others then if sqlerrm<>'duplicate_catalog_code' then raise;end if;end;
 sample:=jsonb_set(sample,'{0,price_purchase}','0'::jsonb);
 perform public.mediuse_catalog_import(sample,'transaction-test',v);
 if (select count(*) from public.mediuse_catalog_items)<>2 or(select version from public.mediuse_catalog_meta where id)<>v+1 then raise exception 'Atomic import failed';end if;
 if (select price_purchase from public.mediuse_catalog_items where code=sample->0->>'code')<>0 then raise exception 'Zero price discarded'; end if;
 perform set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',true);
 r:=public.mediuse_catalog_search('medtronic');
 if r->'items'<>'[]'::jsonb or r->'meta'<>'null'::jsonb or(r->>'total')::int<>0 then raise exception 'Nonmember read allowed';end if;
 begin perform public.mediuse_catalog_import(sample,'outsider',v+1);raise exception 'Nonmember import accepted';exception when others then if sqlerrm<>'access_denied' then raise;end if;end;
 execute 'reset role';execute 'set local role anon';
 begin perform public.mediuse_catalog_search('medtronic');raise exception 'Anonymous search accepted';exception when insufficient_privilege then null;end;
 begin perform count(*) from public.mediuse_catalog_items;raise exception 'Anonymous table read accepted';exception when insufficient_privilege then null;end;
 execute 'reset role';
end $$;
rollback;
select 'Catalog search, access control and atomic import checks passed; test writes rolled back' as result;
